# Generated by Django 5.1.2 on 2024-11-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
